<?php
/**
 * @var $this Mage_Adminhtml_Block_Sales_Order_Create_Items_Grid
 */
?>

<!-- Warehouse -->
<?php $helper                       = $this->helper('warehouse') ?>
<?php $config                       = $helper->getConfig() ?>
<!-- End Warehouse -->

<?php $_items = $this->getItems() ?>
<?php if (empty($_items)): ?>
	<div class="grid" id="order-items_grid">
		<table cellspacing="0" class="data order-tables">
			<col />

			<!-- Warehouse -->
			<col />
			<!-- End Warehouse -->

			<col width="250" />
			<col width="80" />
			<col width="100" />
			<col width="80" />
			<col width="100" />
			<col width="80" />
			<thead>
			<tr class="headings">
				<th class="no-link" style="min-width: 250px"><?php echo $this->helper('sales')->__('Product') ?></th>
                <th class="no-link" style="min-width: 20px"><?php echo $this->helper('sales')->__('Configurate') ?></th>


				<th class="no-link" style="min-width: 120px"><?php echo $this->helper('sales')->__('SKU') ?></th>
				<?php
				if(Mage::getStoreConfig(ITwebexperts_Payperrentals_Helper_Data::XML_PATH_STARTEND_SHOW_AS_COLUMNS) == 1): ?>
					<th class="no-link"><?php echo $this->helper('sales')->__('Start') ?></th>
					<th class="no-link"><?php echo $this->helper('sales')->__('End') ?></th>
                <?php endif; ?>
                <!-- Warehouse -->
                <th class="no-link"><?php echo $helper->__('Warehouse') ?></th>
                <!-- End Warehouse -->
				<th class="no-link"><?php echo $this->helper('sales')->__('Price') ?></th>
				<th class="no-link"><?php echo $this->helper('sales')->__('Qty') ?></th>
				<th class="no-link"><?php echo $this->helper('sales')->__('Subtotal') ?></th>
				<th class="no-link"><?php echo $this->helper('sales')->__('Discount') ?></th>
				<th class="no-link"><?php echo $this->helper('sales')->__('Row Subtotal') ?></th>

				<th class="no-link last"><?php echo $this->helper('sales')->__('Action') ?></th>
			</tr>
			</thead>
			<tbody>
			<tr class="even">
				<td class="empty-text a-center" colspan="100"><?php echo $this->helper('sales')->__('No ordered items') ?></td>
			</tr>
			</tbody>
		</table>
	</div>
<?php else: ?>
	<div>
	<?php if(count($_items)>10): ?>
		<p class="a-right">

			<!-- Warehouse -->
			<?php if ($config->isMultipleMode()) : ?>
				<?php echo $this->getButtonHtml($this->helper('sales')->__('Reset Items'),'order.itemsReset()'); ?>
			<?php endif ?>
			<!-- End Warehouse -->


			<?php echo $this->getButtonHtml($this->helper('sales')->__('Update Items and Qty\'s'),'order.itemsUpdate()'); ?>
		</p>
	<?php endif; ?>
	<div class="grid" id="order-items_grid">
	<table cellspacing="0" class="data order-tables">
	<col />


	<!-- Warehouse -->
	<col />
	<!-- End Warehouse -->


	<col width="250" />
	<col width="100" />
	<col width="80"  />
	<col width="100" />
	<col width="80"  />
	<col width="100" />
	<col width="80" />
	<thead>
	<tr class="headings">
		<th class="no-link" colspan="2"  style="min-width: 250px"><?php echo $this->helper('sales')->__('Product') ?></th>
        <th class="no-link" style="min-width: 20px"><?php echo $this->helper('sales')->__('Configurate') ?></th>
		<th class="no-link" style="min-width: 120px"><?php echo $this->helper('sales')->__('SKU') ?></th>
		<?php
		if(Mage::getStoreConfig(ITwebexperts_Payperrentals_Helper_Data::XML_PATH_STARTEND_SHOW_AS_COLUMNS) == 1): ?>
			<th class="no-link"><?php echo $this->helper('sales')->__('Start') ?></th>
			<th class="no-link"><?php echo $this->helper('sales')->__('End') ?></th>
		<?php endif; ?>
        <!-- Warehouse -->
        <th class="no-link"><?php echo $helper->__('Warehouse') ?></th>
        <!-- End Warehouse -->
		<th class="no-link"><?php echo $this->helper('sales')->__('Price') ?></th>
		<th class="no-link"><?php echo $this->helper('sales')->__('Qty') ?></th>
		<th class="no-link"><?php echo $this->helper('sales')->__('Subtotal') ?></th>
		<th class="no-link"><?php echo $this->helper('sales')->__('Discount') ?></th>
		<th class="no-link"><?php echo $this->helper('sales')->__('Row Subtotal') ?></th>

		<th class="no-link last"><?php echo $this->helper('sales')->__('Action') ?></th>
	</tr>
	</thead>
	<tfoot>
	<tr>

		<!-- Warehouse -->
		<td class="a-left" colspan="3"><?php echo $this->helper('sales')->__('Total %d product(s)', count($_items)) ?></td>
		<!-- End Warehouse -->

		<td class="a-left" colspan="5"><?php echo $this->helper('sales')->__('Total %d product(s)', count($_items)) ?></td>
		<td colspan="2" class="a-right"><?php echo $this->helper('sales')->__('Subtotal:') ?></td>
		<td class="price"><strong><?php echo $this->formatPrice($this->getSubtotal()) ?></strong></td>
		<td class="price"><strong><?php echo $this->formatPrice($this->getDiscountAmount()) ?></strong></td>
		<td class="price"><strong>
				<?php
				echo $this->formatPrice($this->getSubtotal() + $this->getDiscountAmount());
				?></strong></td>
	</tr>
	</tfoot>
	<?php $i=0 ?>
	<?php foreach ($_items as $_item):$i++ ?>
		<tbody id="tbody_order_item_<?php echo $_item->getId() ?>" class="<?php echo ($i%2)?'even':'odd' ?>">
		<tr>
		<td colspan="2" class="a-left">
			<img alt="" id="detailImg" onclick="window.open('<?php echo Mage::getUrl('adminhtml/catalog_product/edit/', array('id' => $_item->getProductId(), 'tab' =>'product_info_tabs_Payperrentals','detailsonly' => '1', 'key' => Mage::getSingleton('adminhtml/url')->getSecretKey('catalog_product','edit')));?>','Product Details','location=no, toolbar=no,directories=no,status=no,menubar=no,scrollbars=yes,copyhistory=no,resizable=yes,width=1000,height=430');return false;" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS) .'itwebexperts_payperrentals/images/details-icon_1.png';?>" style="cursor: pointer;display:inline-block;vertical-align: middle;width:16px;margin-right: 10px;"/>
			<h5 style="display:inline-block;vertical-align: middle;margin-right: 10px;width:180px;" class="title"><span id="order_item_<?php echo $_item->getId() ?>_title"><?php echo $this->htmlEscape($_item->getName()) ?></span></h5>
			<!--<a href="#" class="customoptiontoggle" style="display:inline-block;vertical-align: middle;margin-right: 10px;"> +Custom Options</a>-->
			<!--<span style="display:inline-block;vertical-align: middle;margin-right: 10px;"><?php echo $this->getConfigureButtonHtml($_item) ?></span>-->

			<!--<div>
                                <strong><?php echo $this->helper('sales')->__('SKU') ?>:</strong>
                                <?php echo implode('<br />', Mage::helper('catalog')->splitSku($this->escapeHtml($_item->getSku()))); ?>
                            </div>-->


			<?php
			//if show start end dates on order editor

			if(Mage::getStoreConfig(ITwebexperts_Payperrentals_Helper_Data::XML_PATH_STARTEND_SHOW_AS_TEXT) == 1){
				if($_item->getProductType() == ITwebexperts_Payperrentals_Helper_Data::PRODUCT_TYPE || $_item->getProductType() == ITwebexperts_Payperrentals_Helper_Data::PRODUCT_TYPE_CONFIGURABLE || $_item->getProductType() == ITwebexperts_Payperrentals_Helper_Data::PRODUCT_TYPE_BUNDLE){
					?>
					<div>
						<strong><?php echo $this->helper('sales')->__('Start Date') ?>:</strong>
						<?php

						$buyRequest = $_item->getBuyRequest();
						echo $buyRequest->getStartDate();
						?>
					</div>
					<div>
						<strong><?php echo $this->helper('sales')->__('End Date') ?>:</strong>
						<?php echo $buyRequest->getEndDate(); ?>
					</div>

					<?php
					$attributes = array();
					$superAttributes = array();
					if($buyRequest->getSuperAttribute()){
						$superAttributes = $buyRequest->getSuperAttribute();
					}

					foreach($superAttributes as $attributeId => $attributeValue){

						$collection = Mage::getResourceModel('eav/entity_attribute_collection')
							//->setEntityTypeFilter($_item->getProductType())
							->addFieldToFilter('attribute_id', $attributeId);
						//->addFieldToFilter('attribute_value', $attributeValue);
						$product = Mage::getModel('catalog/product');

						$_attribute = $collection->getFirstItem()->setEntity($product->getResource());
						//Zend_Debug::dump($_attribute->getData());
						echo '<b>'.$_attribute->getFrontendLabel().':</b> ';
						$attribute_options  = $_attribute->getSource()->getAllOptions(false);
						foreach($attribute_options as $attr){
							if($attr['value'] == $attributeValue){
								echo $attr['label'].'<br/>';
								break;
							}

						}

						//$Product = Mage::getModel('catalog/product')->load($_item->getProductId());
						//$attribute = $Product->getTypeInstance(true)->getAttributeById($attributeId, $Product);
						//$attributesArr = array();
						//$attributesArr['attribute'] = $attribute;
						//$attribute->
						//$attributesArr['code'] = $attributeCode;
						//$attributes[] = $attributesArr;
					}
				}

			}
			?>
			<?php if($_item->getMessage(false)): ?>


				<!-- Warehouse -->
				<?php if ($helper->getVersionHelper()->isGe1600()) : ?>
					<?php foreach ($_item->getMessage(false) as $message): ?>
						<div class="<?php if($_item->getHasError()): ?>error<?php else: ?>notice<?php endif; ?>">
							<div style="font-size:95%"><?php echo $message; ?></div>
						</div>
					<?php endforeach; ?>
				<?php else : ?>
					<?php if($_item->getHasError()): ?>
						<div class="error">
							<div style="font-size:95%"><?php echo $this->helper('sales')->__('This product has not been configured.') ?></div>
						</div>
					<?php else: ?>
						<?php foreach ($_item->getMessage(false) as $message): ?>
							<div class="notice">
								<div style="font-size:95%"><?php echo Mage::helper('core')->escapeHtml($message); ?></div>
							</div>
						<?php endforeach; ?>
					<?php endif; ?>
				<?php endif; ?>
				<!-- End Warehouse -->



			<?php endif; ?>
		</td>
        <td class="a-center"><img alt="" onclick="<?php echo sprintf('order.showQuoteItemConfiguration(%s)', $_item->getId());?>;" id="configureImg" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS) .'itwebexperts_payperrentals/images/tools_icon_1.png';?>" style="cursor: pointer;display:inline-block;vertical-align: middle;width:16px;margin-right: 10px;"/></td>


		<td class="a-left"><?php echo implode('<br />', Mage::helper('catalog')->splitSku($this->escapeHtml($_item->getSku()))); ?></td>
		<?php
		if(Mage::getStoreConfig(ITwebexperts_Payperrentals_Helper_Data::XML_PATH_STARTEND_SHOW_AS_COLUMNS) == 1){
			$stDate = '';
			$enDate = '';
			if($_item->getProductType() == ITwebexperts_Payperrentals_Helper_Data::PRODUCT_TYPE || $_item->getProductType() == ITwebexperts_Payperrentals_Helper_Data::PRODUCT_TYPE_CONFIGURABLE || $_item->getProductType() == ITwebexperts_Payperrentals_Helper_Data::PRODUCT_TYPE_BUNDLE){
				$buyRequest = $_item->getBuyRequest();
				$stDate = ITwebexperts_Payperrentals_Helper_Data::formatDbDate($buyRequest->getStartDate());
				$enDate = ITwebexperts_Payperrentals_Helper_Data::formatDbDate($buyRequest->getEndDate());
			}
			?>
			<td class="price"><?php echo $stDate;?></td>
			<td class="price"><?php echo $enDate;?></td>
		<?php
		}
		?>

		<!-- Warehouse -->
		<td class="a-left v-middle">
			<?php if ($config->isMultipleMode()) : ?>
				<?php $warehouses = $_item->getInStockWarehouses() ?>
				<select name="item[<?php echo $_item->getId() ?>][stock_id]" title="<?php echo $helper->__('Warehouse') ?>">
					<?php foreach ($warehouses as $warehouse) : ?>
						<option value="<?php echo $warehouse->getStockId() ?>"<?php if ($warehouse->getStockId() == $_item->getStockId()) : ?> selected="selected"<?php endif; ?>><?php echo $warehouse->getTitle() ?></option>
					<?php endforeach; ?>
				</select>
			<?php else : ?>
				<?php if ($_item->getWarehouse()) : ?>
					<?php echo $_item->getWarehouseTitle() ?>
				<?php else : ?>
					<?php echo $helper->__('No warehouse') ?>
				<?php endif; ?>
			<?php endif; ?>
		</td>
		<!-- End Warehouse -->

		<td class="price">




			<?php if ($this->helper('tax')->displayCartPriceExclTax($this->getStore()) || $this->helper('tax')->displayCartBothPrices($this->getStore())): ?>
				<?php if ($this->helper('tax')->displayCartBothPrices($this->getStore())): ?>
					<span class="label"><?php echo $this->__('Excl. Tax'); ?>:</span>
				<?php endif; ?>
				<?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales')): ?>
					<?php echo $this->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?>
				<?php else: ?>
					<?php echo $this->formatPrice($_item->getCalculationPrice()) ?>
				<?php endif; ?>


				<?php if (Mage::helper('weee')->getApplied($_item)): ?>
					<br />
					<?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales')): ?>
						<small>
							<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
								<span class="nobr"><?php echo $tax['title']; ?>: <?php echo $this->formatPrice($tax['amount'],true,true); ?></span><br />
							<?php endforeach; ?>
						</small>
					<?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
						<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
							<span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo $this->formatPrice($tax['amount_incl_tax'],true,true); ?></small></span><br />
						<?php endforeach; ?>
					<?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales')): ?>
						<small>
							<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
								<span class="nobr"><?php echo $tax['title']; ?>: <?php echo $this->formatPrice($tax['amount_incl_tax'],true,true); ?></span><br />
							<?php endforeach; ?>
						</small>
					<?php endif; ?>

					<?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
						<br />
						<span class="nobr"><?php echo Mage::helper('weee')->__('Total'); ?>:<br /> <?php echo $this->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?></span>
					<?php endif; ?>
				<?php endif; ?>
			<?php endif; ?>


			<?php if ($this->helper('tax')->displayCartPriceInclTax($this->getStore()) || $this->helper('tax')->displayCartBothPrices($this->getStore())): ?>
				<?php if ($this->helper('tax')->displayCartBothPrices($this->getStore())): ?>
					<br /><span class="label"><?php echo $this->__('Incl. Tax'); ?>:</span>
				<?php endif; ?>
				<?php $_incl = $this->helper('checkout')->getPriceInclTax($_item); ?>
				<?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales')): ?>
					<?php echo $this->formatPrice($_incl+$_item->getWeeeTaxAppliedAmount()); ?>
				<?php else: ?>
					<?php echo $this->formatPrice($_incl-$_item->getWeeeTaxDisposition()) ?>
				<?php endif; ?>
				<?php if (Mage::helper('weee')->getApplied($_item)): ?>
					<br />
					<?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales')): ?>
						<small>
							<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
								<span class="nobr"><?php echo $tax['title']; ?>: <?php echo $this->formatPrice($tax['amount'],true,true); ?></span><br />
							<?php endforeach; ?>
						</small>
					<?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
						<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
							<span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo $this->formatPrice($tax['amount_incl_tax'],true,true); ?></small></span><br />
						<?php endforeach; ?>
					<?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales')): ?>
						<small>
							<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
								<span class="nobr"><?php echo $tax['title']; ?>: <?php echo $this->formatPrice($tax['amount_incl_tax'],true,true); ?></span><br />
							<?php endforeach; ?>
						</small>
					<?php endif; ?>

					<?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
						<span class="nobr"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>:<br /> <?php echo $this->formatPrice($_incl+$_item->getWeeeTaxAppliedAmount()); ?></span>
					<?php endif; ?>
				<?php endif; ?>
			<?php endif; ?>




			<?php $_isCustomPrice = $this->usedCustomPriceForItem($_item) ?>
			<?php if($_tier = $this->getTierHtml($_item)): ?>
				<div id="item_tier_block_<?php echo $_item->getId() ?>"<?php if ($_isCustomPrice): ?> style="display:none"<?php endif; ?>>
					<a href="#" onclick="$('item_tier_<?php echo $_item->getId() ?>').toggle();return false;"><?php echo $this->helper('sales')->__('Tier Pricing') ?></a>
					<div style="display:none" id="item_tier_<?php echo $_item->getId() ?>"><?php echo $_tier ?></div>
				</div>
			<?php endif; ?>
			<?php if ($this->canApplyCustomPrice($_item)): ?>
				<div class="nobr">
					<input type="checkbox" id="item_use_custom_price_<?php echo $_item->getId() ?>"<?php if ($_isCustomPrice): ?> checked="checked"<?php endif; ?> onclick="order.toggleCustomPrice(this, 'item_custom_price_<?php echo $_item->getId() ?>', 'item_tier_block_<?php echo $_item->getId() ?>');"/>
					<label class="normal" for="item_use_custom_price_<?php echo $_item->getId() ?>"><?php echo $this->helper('sales')->__('Custom Price') ?>*</label>
				</div>
			<?php endif; ?>
			<input id="item_custom_price_<?php echo $_item->getId() ?>" name="item[<?php echo $_item->getId() ?>][custom_price]" value="<?php echo sprintf("%.2f", $this->getOriginalEditablePrice($_item))?>"<?php if (!$_isCustomPrice): ?> style="display:none" disabled="disabled"<?php endif; ?> class="input-text item-price"/>
		</td>
		<td><input name="item[<?php echo $_item->getId() ?>][qty]" class="input-text item-qty" value="<?php echo $_item->getQty()*1 ?>" maxlength="12" /></td>
		<td class="price">




			<?php if ($this->helper('tax')->displayCartPriceExclTax($this->getStore()) || $this->helper('tax')->displayCartBothPrices($this->getStore())): ?>
				<?php if ($this->helper('tax')->displayCartBothPrices($this->getStore())): ?>
					<span class="label"><?php echo $this->__('Excl. Tax'); ?>:</span>
				<?php endif; ?>
				<?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales')): ?>
					<?php echo $this->formatPrice($_item->getRowTotal()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()); ?>
				<?php else: ?>
					<?php echo $this->formatPrice($_item->getRowTotal()) ?>
				<?php endif; ?>


				<?php if (Mage::helper('weee')->getApplied($_item)): ?>
					<br />
					<?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales')): ?>
						<small>
							<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
								<span class="nobr"><?php echo $tax['title']; ?>: <?php echo $this->formatPrice($tax['row_amount'],true,true); ?></span><br />
							<?php endforeach; ?>
						</small>
					<?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
						<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
							<span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo $this->formatPrice($tax['row_amount_incl_tax'],true,true); ?></small></span><br />
						<?php endforeach; ?>
					<?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales')): ?>
						<small>
							<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
								<span class="nobr"><?php echo $tax['title']; ?>: <?php echo $this->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span><br />
							<?php endforeach; ?>
						</small>
					<?php endif; ?>

					<?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
						<br />
						<span class="nobr"><?php echo Mage::helper('weee')->__('Total'); ?>:<br /> <?php echo $this->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()); ?></span>
					<?php endif; ?>
				<?php endif; ?>
			<?php endif; ?>


			<?php if ($this->helper('tax')->displayCartPriceInclTax($this->getStore()) || $this->helper('tax')->displayCartBothPrices($this->getStore())): ?>
				<?php if ($this->helper('tax')->displayCartBothPrices($this->getStore())): ?>
					<br /><span class="label"><?php echo $this->__('Incl. Tax'); ?>:</span>
				<?php endif; ?>
				<?php $_incl = $this->helper('checkout')->getSubtotalInclTax($_item); ?>
				<?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales')): ?>
					<?php echo $this->formatPrice($_incl+$_item->getWeeeTaxAppliedRowAmount()); ?>
				<?php else: ?>
					<?php echo $this->formatPrice($_incl-$_item->getWeeeTaxRowDisposition()) ?>
				<?php endif; ?>
				<?php if (Mage::helper('weee')->getApplied($_item)): ?>
					<br />
					<?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales')): ?>
						<small>
							<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
								<span class="nobr"><?php echo $tax['title']; ?>: <?php echo $this->formatPrice($tax['row_amount'],true,true); ?></span><br />
							<?php endforeach; ?>
						</small>
					<?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
						<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
							<span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo $this->formatPrice($tax['row_amount_incl_tax'],true,true); ?></small></span><br />
						<?php endforeach; ?>
					<?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales')): ?>
						<small>
							<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
								<span class="nobr"><?php echo $tax['title']; ?>: <?php echo $this->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span><br />
							<?php endforeach; ?>
						</small>
					<?php endif; ?>

					<?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
						<span class="nobr"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>:<br /> <?php echo $this->formatPrice($_incl+$_item->getWeeeTaxAppliedRowAmount()); ?></span>
					<?php endif; ?>
				<?php endif; ?>
			<?php endif; ?>



		</td>
		<td class="price">
			<?php echo $this->formatPrice(-$_item->getDiscountAmount()) ?><br />
			<input id="item_use_discount_<?php echo $_item->getId() ?>" name="item[<?php echo $_item->getId() ?>][use_discount]"<?php if (!$_item->getNoDiscount()): ?>checked="checked"<?php endif; ?> value="1" type="checkbox" />
			<label for="item_use_discount_<?php echo $_item->getId() ?>" class="normal"><?php echo $this->helper('sales')->__('Apply') ?></label>
		</td>
		<td class="price">


			<?php if ($this->helper('tax')->displayCartPriceExclTax($this->getStore()) || $this->helper('tax')->displayCartBothPrices($this->getStore())): ?>
				<?php $_rowTotalWithoutDiscount = $_item->getPriceInclTax() * $_item->getQty() - $_item->getDiscountAmount() - $_item->getTaxAmount(); ?>
				<?php if ($this->helper('tax')->displayCartBothPrices($this->getStore())): ?>
					<span class="label"><?php echo $this->__('Excl. Tax'); ?>:</span>
				<?php endif; ?>
				<?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales')): ?>
					<?php echo $this->formatPrice(max(0, $_rowTotalWithoutDiscount+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition())); ?>
				<?php else: ?>
					<?php echo $this->formatPrice(max(0, $_rowTotalWithoutDiscount)) ?>
				<?php endif; ?>


				<?php if (Mage::helper('weee')->getApplied($_item)): ?>
					<br />
					<?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales')): ?>
						<small>
							<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
								<span class="nobr"><?php echo $tax['title']; ?>: <?php echo $this->formatPrice($tax['row_amount'],true,true); ?></span><br />
							<?php endforeach; ?>
						</small>
					<?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
						<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
							<span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo $this->formatPrice($tax['row_amount_incl_tax'],true,true); ?></small></span><br />
						<?php endforeach; ?>
					<?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales')): ?>
						<small>
							<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
								<span class="nobr"><?php echo $tax['title']; ?>: <?php echo $this->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span><br />
							<?php endforeach; ?>
						</small>
					<?php endif; ?>

					<?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
						<br />
						<span class="nobr"><?php echo Mage::helper('weee')->__('Total'); ?>:<br /> <?php echo $this->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()); ?></span>
					<?php endif; ?>
				<?php endif; ?>
			<?php endif; ?>


			<?php if ($this->helper('tax')->displayCartPriceInclTax($this->getStore()) || $this->helper('tax')->displayCartBothPrices($this->getStore())): ?>
				<?php if ($this->helper('tax')->displayCartBothPrices($this->getStore())): ?>
					<br /><span class="label"><?php echo $this->__('Incl. Tax'); ?>:</span>
				<?php endif; ?>
				<?php $_incl = $_item->getPriceInclTax() * $_item->getQty() - $_item->getDiscountAmount(); ?>
				<?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales')): ?>
					<?php echo $this->formatPrice($_incl+$_item->getWeeeTaxAppliedRowAmount()); ?>
				<?php else: ?>
					<?php echo $this->formatPrice($_incl-$_item->getWeeeTaxRowDisposition()) ?>
				<?php endif; ?>
				<?php if (Mage::helper('weee')->getApplied($_item)): ?>
					<br />
					<?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales')): ?>
						<small>
							<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
								<span class="nobr"><?php echo $tax['title']; ?>: <?php echo $this->formatPrice($tax['row_amount'],true,true); ?></span><br />
							<?php endforeach; ?>
						</small>
					<?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
						<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
							<span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo $this->formatPrice($tax['row_amount_incl_tax'],true,true); ?></small></span><br />
						<?php endforeach; ?>
					<?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales')): ?>
						<small>
							<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
								<span class="nobr"><?php echo $tax['title']; ?>: <?php echo $this->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span><br />
							<?php endforeach; ?>
						</small>
					<?php endif; ?>

					<?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
						<span class="nobr"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>:<br /> <?php echo $this->formatPrice($_incl+$_item->getWeeeTaxAppliedRowAmount()); ?></span>
					<?php endif; ?>
				<?php endif; ?>
			<?php endif; ?>

		</td>
		<td class="last">
			<select name="item[<?php echo $_item->getId() ?>][action]" style="width:100px;">
				<option value=""></option>
				<option value="remove"><?php echo $this->helper('sales')->__('Remove') ?></option>
				<?php if($this->getCustomerId() && $this->getMoveToCustomerStorage()): ?>
					<option value="cart"><?php echo $this->helper('sales')->__('Move to Shopping Cart') ?></option>
					<?php if ($this->isMoveToWishlistAllowed($_item)): ?>
						<?php $wishlists = $this->getCustomerWishlists();?>
						<?php if (count($wishlists) <= 1):?>
							<option value="wishlist"><?php echo $this->helper('sales')->__('Move to Wishlist') ?></option>
						<?php else: ?>
							<optgroup label="<?php echo $this->helper('sales')->__('Move to Wishlist') ?>">
								<?php foreach ($wishlists as $wishlist):?>
									<option value="wishlist_<?php echo $wishlist->getId();?>"><?php echo $this->escapeHtml($wishlist->getName());?></option>
								<?php endforeach;?>
							</optgroup>
						<?php endif; ?>
					<?php endif; ?>
				<?php endif; ?>
			</select>
		</td>
		</tr>
		<?php echo $this->getItemExtraInfo($_item)->toHtml(); ?>
		</tbody>
	<?php endforeach; ?>
	</table>
	</div>
	<table cellspacing="0" width="100%">
		<col width="50%" />
		<col width="50%" />
		<tr>
			<td class="a-left"><small><?php echo $this->getInclExclTaxMessage(); ?></small></td>
			<td class="a-right">

				<!-- Warehouse -->
				<?php if ($config->isMultipleMode()) : ?>
					<?php echo $this->getButtonHtml($this->helper('sales')->__('Reset Items'),'order.itemsReset()'); ?>
				<?php endif ?>
				<!-- End Warehouse -->

				<?php echo $this->getButtonHtml($this->helper('sales')->__('Update Items and Qty\'s'),'order.itemsUpdate()'); ?>
			</td>
		</tr>
	</table>
	<br />
	<div id="order-coupons"><?php echo $this->getChildHtml();?></div>
	<div class="clear"></div>
	<script type="text/javascript">order.itemsOnchangeBind()</script>
	</div>
	<script type="text/javascript">
		//$jppr1(document).ready(function(){
		function getScripts(names, callback) {
			var received = 0;
			var realCallback = function() {
				received++;
				if (received === names.length)
					$jppr1(callback);
			};

			for (var i = 0; i < names.length; i++)
				$jppr1.getScript(names[i], realCallback);
		}
		getScripts([ "<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS) .'itwebexperts_payperrentals/jqueryui/js/jquery-ui-1.9.2.custom.js'; ?>", "<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS) .'itwebexperts_payperrentals/qtip/jquery.qtip.js'; ?>" ], function() {

			var fixHelperModified = function(e, tr) {
					var $originals = tr.children();
					var $helper = tr.clone();
					$helper.children().each(function(index) {
						$jppr1(this).width($originals.eq(index).width())
					});
					return $helper;
				},
				updateIndex = function(e, ui) {
					/*$jppr('td.index', ui.item.parent()).each(function (i) {
					 $(this).html(i + 1);
					 });*/
				};
			$jppr1("#order-items_grid table thead").addClass('ui-state-disabled-line');
			$jppr1("#order-items_grid table tfoot").addClass('ui-state-disabled-line');
			$jppr1("#order-items_grid table colgroup").addClass('ui-state-disabled-line');
			$jppr1("#order-items_grid table")./*find('tbody').*/sortable({
				/*helper: fixHelperModified,
				 stop: updateIndex*/
				items: "tbody:not(.ui-state-disabled-line)",
				placeholder: "ui-state-highlight",
				update: function(event, ui) {

					Element.show('loading-mask');
					$jppr1.ajax({
						cache: false,
						dataType: 'json',
						type: 'post',
						url: '<?php echo Mage::getUrl("payperrentals_admin/adminhtml_ajax/reorderQuoteItems/",array('form_key'=> Mage::getSingleton('core/session')->getFormKey()))?>',
						data: 'data='+$jppr1("#order-items_grid table").sortable('toArray').toString(),
						success: function (data) {
							Element.hide('loading-mask');
						}
					});

				}
			});

			//Element.show('loading-mask');
			$jppr1.ajax({
				cache: false,
				dataType: 'json',
				type: 'post',
				url: '<?php echo Mage::getUrl("payperrentals_admin/adminhtml_ajax/getOverbooked/",array('form_key'=> Mage::getSingleton('core/session')->getFormKey()))?>',
				success: function (data) {
					for(var i=0;i < data.ids.length;i++){
						$jppr1('#'+data.ids[i]+' tr td').css('background', '#ff0000');
						$jppr1('#'+data.ids[i]).qtip({
							content: {
								text: data.idstext[data.ids[i]],
								title: {
									text: 'Overbooking Details - Click on product name for report'
								}
							},
							position: {
								at: 'top left',
								adjust: {
									y: -80,
									x: -30
								}
							},
							style: { classes: 'qtip-shadow qtip-red' }
						});
						$jppr1('#'+data.ids[i]+ ' h5').click(function(){
							//alert(data.ids[i]);
							//alert($jppr1(this).attr('id'));
							var prodNam = $jppr1(this).parent().parent().parent().attr('id');
							window.open('<?php echo Mage::getUrl('payperrentals_admin/adminhtml_quantityreport/index/', array( 'detailsonly' => '1', 'key' => Mage::getSingleton('adminhtml/url')->getSecretKey('adminhtml_quantityreport','index')));?>'+'productName/'+data.idsproduct[prodNam]+'/gotoDate/'+data.idsdate[prodNam],'Quantity Report Details','location=no, toolbar=no,directories=no,status=no,menubar=no,scrollbars=yes,copyhistory=no,resizable=yes,width=1000,height=430');
							return false;
						});
					}
					// Element.hide('loading-mask');
				}
			});

		});
		AdminOrder.prototype.loadAreaResponseHandler = AdminOrder.prototype.loadAreaResponseHandler.wrap(function(parentMethod,response){
			if (response.error) {
				alert(response.message);
			}
			if(response.ajaxExpired && response.ajaxRedirect) {
				setLocation(response.ajaxRedirect);
			}
			if(!this.loadingAreas){
				this.loadingAreas = [];
			}
			if(typeof this.loadingAreas == 'string'){
				this.loadingAreas = [this.loadingAreas];
			}
			if(this.loadingAreas.indexOf('message'==-1)) this.loadingAreas.push('message');
			for(var i=0; i<this.loadingAreas.length; i++){
				var id = this.loadingAreas[i];
				if($(this.getAreaId(id))){
					if ('message' != id || response[id]) {
						var wrapper = new Element('div');
						wrapper.update(response[id] ? response[id] : '');
						$(this.getAreaId(id)).update(wrapper);
					}
					if ($(this.getAreaId(id)).callback) {
						this[$(this.getAreaId(id)).callback]();
					}
				}
			}
			$jppr1("#order-items_grid table thead").addClass('ui-state-disabled-line');
			$jppr1("#order-items_grid table tfoot").addClass('ui-state-disabled-line');
			$jppr1("#order-items_grid table colgroup").addClass('ui-state-disabled-line');
			$jppr1("#order-items_grid table")./*find('tbody').*/sortable({
				/*helper: fixHelperModified,
				 stop: updateIndex*/
				items: "tbody:not(.ui-state-disabled-line)",
				placeholder: "ui-state-highlight",
				update: function(event, ui) {

					Element.show('loading-mask');
					$jppr1.ajax({
						cache: false,
						dataType: 'json',
						type: 'post',
						url: '<?php echo Mage::getUrl("payperrentals_admin/adminhtml_ajax/reorderQuoteItems/",array('form_key'=> Mage::getSingleton('core/session')->getFormKey()))?>',
						data: 'data='+$jppr1("#order-items_grid table").sortable('toArray').toString(),
						success: function (data) {
							Element.hide('loading-mask');
						}
					});

				}
			});
			//todo!!!!! I go item by item in the quote using tbody id and I add an inventory_check, if is overbook, I make the row red and i add a qtip to say click for details, and on row click  I add an open window going to quantity report, already setup for the product and the date and also hiding the header.
			//check availability I will use the quote details and only returning if is overbooked.
			/*var myids = [];
			 $jppr1("#order-items_grid table tbody:not(.ui-state-disabled-line)").each(function(){
			 myids.push($jppr1(this).attr('id'));
			 });*/

			// Element.show('loading-mask');
			$jppr1.ajax({
				cache: false,
				dataType: 'json',
				type: 'post',
				url: '<?php echo Mage::getUrl("payperrentals_admin/adminhtml_ajax/getOverbooked/",array('form_key'=> Mage::getSingleton('core/session')->getFormKey()))?>',
				/*data: 'data='+myids,*/
				success: function (data) {
					for(var i=0;i < data.ids.length;i++){
						$jppr1('#'+data.ids[i]+' tr td').css('background', '#ff0000');
						$jppr1('#'+data.ids[i]).qtip({
							content: {
								text: data.idstext[data.ids[i]],
								title: {
									text: 'Overbooking Details - Click on product name for report'
								}
							},
							position: {
								at: 'top left',
								adjust: {
									y: -80,
									x: -30
								}
							},
							style: { classes: 'qtip-shadow qtip-red' }
						});
						$jppr1('#'+data.ids[i]+' h5').click(function(){
							//alert(data.ids[i]);
							//alert($jppr1(this).attr('id'));
							var prodNam = $jppr1(this).parent().parent().parent().attr('id');
							window.open('<?php echo Mage::getUrl('payperrentals_admin/adminhtml_quantityreport/index/', array( 'detailsonly' => '1', 'key' => Mage::getSingleton('adminhtml/url')->getSecretKey('adminhtml_quantityreport','index')));?>'+'productName/'+data.idsproduct[prodNam]+'/gotoDate/'+data.idsdate[prodNam],'Quantity Report Details','location=no, toolbar=no,directories=no,status=no,menubar=no,scrollbars=yes,copyhistory=no,resizable=yes,width=1000,height=430');
							return false;
						});
					}
					//Element.hide('loading-mask');
				}
			});

		});
		// });
	</script>

	<?php if ($this->isGiftMessagesAvailable()) : ?>
		<script type="text/javascript">
			//<![CDATA[
			/**
			 * Retrieve gift options tooltip content
			 */
			function getGiftOptionsTooltipContent(itemId) {
				var contentLines = [];
				var headerLine = null;
				var contentLine = null;

				$$('#gift_options_data_' + itemId + ' .gift-options-tooltip-content').each(function (element) {
					if (element.down(0)) {
						headerLine = element.down(0).innerHTML;
						contentLine = element.down(0).next().innerHTML;
						if (contentLine.length > 30) {
							contentLine = contentLine.slice(0,30) + '...';
						}
						contentLines.push(headerLine + ' ' + contentLine);
					}
				});
				return contentLines.join('<br/>');
			}
			giftOptionsTooltip.setTooltipContentLoaderFunction(getGiftOptionsTooltipContent);

			//]]>
		</script>
	<?php endif; ?>
<?php endif; ?>
