<?php /* @var $this Innoexts_Warehouse_Block_Adminhtml_Sales_Order_View_Items */ ?>
<?php /* @var $this Mage_Adminhtml_Block_Sales_Order_View_Items */ ?>
<?php /* @var $this Innoexts_Warehouse_Block_Adminhtml_Sales_Order_Invoice_Create_Items */ ?>
<?php /* @var $this Mage_Adminhtml_Block_Sales_Order_Invoice_Create_Items */ ?>
<?php /* @var $this Innoexts_Warehouse_Block_Adminhtml_Sales_Order_Shipment_Create_Items */ ?>
<?php /* @var $this Mage_Adminhtml_Block_Sales_Order_Shipment_Create_Items */ ?>
<?php /* @var $this Innoexts_Warehouse_Block_Adminhtml_Sales_Order_Creditmemo_Create_Items */ ?>
<?php /* @var $this Mage_Adminhtml_Block_Sales_Order_Creditmemo_Create_Items */ ?>
<?php if(Mage::app()->getRequest()->getParam('noHeader')): 	?>
	<style type="text/css">
		.header{
			display:none !important;
		}
		.footer, .notification-global{
			display:none !important;
		}

	</style>
<?php endif ?>

<!-- Warehouse -->
<?php $helper = Mage::helper('warehouse') ?>
<!-- End Warehouse -->

<?php $_order = $this->getOrder() ?>
<div class="grid np">
	<?php
	$isSingle = ITwebexperts_Payperrentals_Helper_Data::isSingleOrder($this->getOrder());
	if($isSingle['bool']){
        echo $this->__('Start date:') . ' ' . $isSingle['start_date'] . ' ' . $this->__('End Date:') . ' ' . $isSingle['end_date'];
	}
	?>
	<div class="hor-scroll">
		<table cellspacing="0" class="data order-tables">
			<col />
			<col width="1" />
			<col width="1" />
			<col width="1" />
			<col width="1" />
			<col width="1" />
			<col width="1" />
			<col width="1" />
			<col width="1" />
			<col width="1" />
			<col width="1" />
			<col width="1" />
			<col width="1" />
			<thead>
			<tr class="headings">
				<th><?php echo $this->helper('sales')->__('Product') ?></th>
				<th><?php echo $helper->__('Warehouse') ?></th>
				<th><span class="nobr"><?php echo $this->helper('sales')->__('Item Status') ?></span></th>
				<th><span class="nobr"><?php echo $this->helper('sales')->__('Original Price') ?></span></th>
				<th><?php echo $this->helper('sales')->__('Price') ?></th>
				<th class="a-center"><?php echo $this->helper('sales')->__('Qty') ?></th>
				<th class="a-center"><?php echo $this->helper('sales')->__('Current Stock') ?></th>
				<th class="a-center"><?php echo $this->helper('sales')->__('Remaining Stock') ?></th>
				<th><?php echo $this->helper('sales')->__('Subtotal') ?></th>
				<th><span class="nobr"><?php echo $this->helper('sales')->__('Tax Amount') ?></span></th>
				<th><span class="nobr"><?php echo $this->helper('sales')->__('Tax Percent') ?></span></th>
				<th><span class="nobr"><?php echo $this->helper('sales')->__('Discount Amount') ?></span></th>
				<th class="last"><span class="nobr"><?php echo $this->helper('sales')->__('Row Total') ?></span></th>
			</tr>
			</thead>
			<?php $_items = $this->getItemsCollection() ?>
			<?php $i=0;foreach ($_items as $_item):?>
				<?php if ($_item->getParentItem()) continue; else $i++;?>
				<tbody class="<?php echo $i%2?'even':'odd' ?>">
				<?php echo $this->getItemHtml($_item) ?>
				<?php echo $this->getItemExtraInfoHtml($_item) ?>
				</tbody>
			<?php endforeach; ?>
		</table>
	</div>
</div>
<br />
<script type="text/javascript">
    function getItemsGridData()
    {
        var productIds = new Array();
        var productIdsFields = $jppr('input[name="stock_product_id"]');
        productIdsFields.each(function(index, element) {
            productIds.push(element.value);
        });
        var pprSearchAjax = $jppr.ajax({
            cache: false,
            dataType: 'json',
            type: 'post',
            url: '<?php echo Mage::getUrl("payperrentals_admin/adminhtml_ajax/getProductsPrices/",array('form_key'=> Mage::getSingleton('core/session')->getFormKey()))?>',
            data: {
                'products': productIds
            },
            success: function (data) {
                var productIdsFields = $jppr('input[name="stock_product_id"]');
                productIdsFields.each(function(index, element) {
                    var productId = element.value;
                    if (data[productId] != undefined) {
                        $jppr(element).parent('td').parent('tr').find('.currentstock').html(data[productId]['avail']);
                        $jppr(element).parent('td').parent('tr').find('.remainingstock').html(data[productId]['remaining']);
                    }
                });
                /*var productIdsTDs = $_jppr('#sales_order_create_search_grid_table tbody tr td:first-child');
                 productIdsTDs.each(function(index, element) {
                 var productId = $_jppr.trim(element.innerHTML);
                 if (data[productId] != undefined) {
                 $_jppr(element).parent('tr').find('.currentstock').html(data[productId]['avail']);
                 }
                 });*/
            }
        });

    }
    Event.observe(window, 'load',  function(){
        getItemsGridData();
    });
</script>