<?php /* @var $this Innoexts_Warehouse_Block_Adminhtml_Sales_Order_View_Items_Renderer_Default */ ?>
<?php /* @var $this Mage_Adminhtml_Block_Sales_Order_View_Items_Renderer_Default */ ?>
<?php $_item = $this->getItem() ?>
<?php
if ($options1 = $this->getItem()->getProductOptions()) {
	//$startDateLabel = $this->getItem()->getIsVirtual() ? $this->__("Subscription start:") : $this->__("First delivery:");
	if(isset($options1['info_buyRequest'])) {
		if(isset($options1['info_buyRequest'][ITwebexperts_Payperrentals_Model_Product_Type_Reservation::START_DATE_OPTION])){
			$start_date = $options1['info_buyRequest'][ITwebexperts_Payperrentals_Model_Product_Type_Reservation::START_DATE_OPTION];
			$end_date =  $options1['info_buyRequest'][ITwebexperts_Payperrentals_Model_Product_Type_Reservation::END_DATE_OPTION];
		}
	}
}
/*if(isset($start_date)){
	$stockArr = ITwebexperts_Payperrentals_Helper_Data::getStock($_item->getProduct()->getId(), $start_date, $end_date, $qty);
	$current_stock = $stockArr['avail'] + $qty;
	$remaining_stock = $stockArr['remaining'] + $qty;
}*/

?>

<!-- Warehouse -->
<?php $helper                       = $this->helper('warehouse') ?>
<!-- End Warehouse -->

<?php $this->setPriceDataObject($_item) ?>
<tr<?php if (!$this->canDisplayGiftmessage()): ?> class="border"<?php endif; ?>>
<td>
	<?php if ($this->canDisplayContainer()): ?>
	<div id="<?php echo $this->getHtmlId() ?>" class="item-container">
		<?php endif; ?>
		<div class="item-text">
            <?php echo $this->getColumnHtml($_item, 'name'); ?>
		</div>
		<?php if ($this->canDisplayContainer()): ?>
	</div>
<?php endif ?>
</td>

<!-- Warehouse -->
<td class="a-left">
	<?php if ($_item->getWarehouse()) : ?>
		<?php echo $_item->getWarehouseTitle() ?>
	<?php else : ?>
		<?php echo $helper->__('No warehouse') ?>
	<?php endif; ?>
</td>
<!-- End Warehouse -->

<td class="a-center"><?php echo $_item->getStatus() ?></td>
<td class="a-right"><?php echo $this->displayPriceAttribute('original_price') ?></td>
<td class="a-right">
	<?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceExclTax()): ?>
		<span class="price-excl-tax">
                <?php if ($this->helper('tax')->displaySalesBothPrices()): ?>
                    <span class="label"><?php echo $this->__('Excl. Tax:'); ?></span>
				<?php endif; ?>

			<?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales', $_item->getStoreId())): ?>
				<?php
				echo $this->displayPrices(
					$_item->getBasePrice()+$_item->getBaseWeeeTaxAppliedAmount()+$_item->getBaseWeeeTaxDisposition(),
					$_item->getPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()
				);
				?>
			<?php else: ?>
				<?php echo $this->displayPrices($_item->getBasePrice(), $_item->getPrice()) ?>
			<?php endif; ?>


			<?php if (Mage::helper('weee')->getApplied($_item)): ?>
				<br />
                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales', $_item->getStoreId())): ?>
					<small>
						<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
							<span class="nobr"><?php echo $tax['title']; ?>: <?php echo $this->displayPrices($tax['base_amount'], $tax['amount']); ?></span>
						<?php endforeach; ?>
					</small>
				<?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales', $_item->getStoreId())): ?>
					<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
						<span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo $this->displayPrices($tax['base_amount_incl_tax'], $tax['amount_incl_tax']); ?></small></span>
					<?php endforeach; ?>
				<?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales', $_item->getStoreId())): ?>
					<small>
						<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
							<span class="nobr"><?php echo $tax['title']; ?>: <?php echo $this->displayPrices($tax['base_amount_incl_tax'], $tax['amount_incl_tax']); ?></span>
						<?php endforeach; ?>
					</small>
				<?php endif; ?>

                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales', $_item->getStoreId())): ?>
					<br />
                        <span class="nobr"><?php echo Mage::helper('payperrentals')->__('Total:'); ?><br />
						<?php
						echo $this->displayPrices(
							$_item->getBasePrice()+$_item->getBaseWeeeTaxAppliedAmount()+$_item->getBaseWeeeTaxDisposition(),
							$_item->getPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()
						);
						?>
                        </span>
				<?php endif; ?>
			<?php endif; ?>
            </span>
		<br />
	<?php endif; ?>
	<?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceInclTax()): ?>
		<span class="price-incl-tax">
                <?php if ($this->helper('tax')->displaySalesBothPrices()): ?>
                    <span class="label"><?php echo $this->__('Incl. Tax:'); ?></span>
				<?php endif; ?>
			<?php $_incl = $this->helper('checkout')->getPriceInclTax($_item); ?>
			<?php $_baseIncl = $this->helper('checkout')->getBasePriceInclTax($_item); ?>

			<?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales', $_item->getStoreId())): ?>
				<?php echo $this->displayPrices($_baseIncl+$_item->getBaseWeeeTaxAppliedAmount(), $_incl+$_item->getWeeeTaxAppliedAmount()); ?>
			<?php else: ?>
				<?php echo $this->displayPrices($_baseIncl-$_item->getBaseWeeeTaxDisposition(), $_incl-$_item->getWeeeTaxDisposition()) ?>
			<?php endif; ?>

			<?php if (Mage::helper('weee')->getApplied($_item)): ?>
				<br />
                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales', $_item->getStoreId())): ?>
					<small>
						<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
							<span class="nobr"><?php echo $tax['title']; ?>: <?php echo $this->displayPrices($tax['base_amount'], $tax['amount']); ?></span>
						<?php endforeach; ?>
					</small>
				<?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales', $_item->getStoreId())): ?>
					<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
						<span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo $this->displayPrices($tax['base_amount_incl_tax'], $tax['amount_incl_tax']); ?></small></span>
					<?php endforeach; ?>
				<?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales', $_item->getStoreId())): ?>
					<small>
						<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
							<span class="nobr"><?php echo $tax['title']; ?>: <?php echo $this->displayPrices($tax['base_amount_incl_tax'], $tax['amount_incl_tax']); ?></span>
						<?php endforeach; ?>
					</small>
				<?php endif; ?>

                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales', $_item->getStoreId())): ?>
					<br />
                        <span class="nobr"><?php echo Mage::helper('payperrentals')->__('Total:'); ?><br /> <?php echo $this->displayPrices($_baseIncl+$_item->getBaseWeeeTaxAppliedAmount(), $_incl+$_item->getWeeeTaxAppliedAmount()); ?></span>
				<?php endif; ?>
			<?php endif; ?>
            </span>
	<?php endif; ?>

</td>
<td><?php echo $this->getColumnHtml($_item, 'qty') ?></td>

    <td>
        <?php /** @var $_item Mage_Sales_Model_Order_Item */
        if($_item->getProduct()->isConfigurable()): ?>
            <?php $_childReservation = array(); ?>
            <?php $_childItems = $_item->getChildrenItems() ?>
            <?php foreach($_childItems as $_childItem): ?>
                <?php /** @var $_childItem Mage_Sales_Model_Order_Item */ ?>
                <?php if($_childItem->getProduct()->getTypeId() == ITwebexperts_Payperrentals_Helper_Data::PRODUCT_TYPE): ?>
                    <?php $_childReservation[] = $_childItem->getProduct()->getId(); ?>
                <?php endif; ?>
            <?php endforeach; ?>
        <?php endif; ?>
        <input type="hidden" class="stock_product_id" dates="<?php echo isset($start_date)?$start_date:''; ?>,<?php echo isset($end_date)?$end_date:'';?>" stock_id="<?php echo $_item->getStockId() ?>" qty="<?php echo $_item->getQtyOrdered();?>" value="<?php echo $_item->getProduct()->getId() ?>"<?php if(isset($_childReservation) && count($_childReservation)): ?> childItems="<?php echo implode(',', $_childReservation) ?>"<?php endif ?>/>
        <span class="currentstock"><img src="<?php echo $this->getSkinUrl('images/ajax-loader.gif') ?>" /></span>
    </td>
    <td><span class="remainingstock"><img src="<?php echo $this->getSkinUrl('images/ajax-loader.gif') ?>" /></span></td>


<td class="a-right">
	<?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceExclTax()): ?>
		<span class="price-excl-tax">
                <?php if ($this->helper('tax')->displaySalesBothPrices()): ?>
                    <span class="label"><?php echo $this->__('Excl. Tax:'); ?></span>
				<?php endif; ?>

			<?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales', $_item->getStoreId())): ?>
				<?php
				echo $this->displayPrices(
					$_item->getBaseRowTotal()+$_item->getBaseWeeeTaxAppliedRowAmount()+$_item->getBaseWeeeTaxRowDisposition(),
					$_item->getRowTotal()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()
				);
				?>
			<?php else: ?>
				<?php echo $this->displayPrices($_item->getBaseRowTotal(), $_item->getRowTotal()) ?>
			<?php endif; ?>


			<?php if (Mage::helper('weee')->getApplied($_item)): ?>
				<?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales', $_item->getStoreId())): ?>
					<small>
						<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
							<span class="nobr"><?php echo $tax['title']; ?>: <?php echo $this->displayPrices($tax['base_row_amount'], $tax['row_amount']); ?></span>
						<?php endforeach; ?>
					</small>
				<?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales', $_item->getStoreId())): ?>
					<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
						<span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo $this->displayPrices($tax['base_row_amount_incl_tax'], $tax['row_amount_incl_tax']); ?></small></span>
					<?php endforeach; ?>
				<?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales', $_item->getStoreId())): ?>
					<small>
						<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
							<span class="nobr"><?php echo $tax['title']; ?>: <?php echo $this->displayPrices($tax['base_row_amount_incl_tax'], $tax['row_amount_incl_tax']); ?></span>
						<?php endforeach; ?>
					</small>
				<?php endif; ?>

                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales', $_item->getStoreId())): ?>
					<br />
                        <span class="nobr"><?php echo Mage::helper('payperrentals')->__('Total'); ?>:<br />
						<?php
						echo $this->displayPrices(
							$_item->getBaseRowTotal()+$_item->getBaseWeeeTaxAppliedRowAmount()+$_item->getBaseWeeeTaxRowDisposition(),
							$_item->getRowTotal()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()
						);
						?>
                        </span>
				<?php endif; ?>
			<?php endif; ?>
            </span>
		<br />
	<?php endif; ?>
	<?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceInclTax()): ?>
		<span class="price-incl-tax">
                <?php if ($this->helper('tax')->displaySalesBothPrices()): ?>
                    <span class="label"><?php echo $this->__('Incl. Tax:'); ?></span>
				<?php endif; ?>
			<?php $_incl = $this->helper('checkout')->getSubtotalInclTax($_item); ?>
			<?php $_baseIncl = $this->helper('checkout')->getBaseSubtotalInclTax($_item); ?>
			<?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales', $_item->getStoreId())): ?>
				<?php echo $this->displayPrices($_baseIncl+$_item->getBaseWeeeTaxAppliedRowAmount(), $_incl+$_item->getWeeeTaxAppliedRowAmount()); ?>
			<?php else: ?>
				<?php echo $this->displayPrices($_baseIncl-$_item->getBaseWeeeTaxRowDisposition(), $_incl-$_item->getWeeeTaxRowDisposition()) ?>
			<?php endif; ?>


			<?php if (Mage::helper('weee')->getApplied($_item)): ?>

				<br />
                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales', $_item->getStoreId())): ?>
					<small>
						<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
							<span class="nobr"><?php echo $tax['title']; ?>: <?php echo $this->displayPrices($tax['base_row_amount'], $tax['row_amount']); ?></span>
						<?php endforeach; ?>
					</small>
				<?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales', $_item->getStoreId())): ?>
					<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
						<span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo $this->displayPrices($tax['base_row_amount_incl_tax'], $tax['row_amount_incl_tax']); ?></small></span>
					<?php endforeach; ?>
				<?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales', $_item->getStoreId())): ?>
					<small>
						<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
							<span class="nobr"><?php echo $tax['title']; ?>: <?php echo $this->displayPrices($tax['base_row_amount_incl_tax'], $tax['row_amount_incl_tax']); ?></span>
						<?php endforeach; ?>
					</small>
				<?php endif; ?>

                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales', $_item->getStoreId())): ?>
                        <br /><span class="nobr"><?php echo Mage::helper('payperrentals')->__('Total'); ?>:<br /> <?php echo $this->displayPrices($_baseIncl+$_item->getBaseWeeeTaxAppliedRowAmount(), $_incl+$_item->getWeeeTaxAppliedRowAmount()); ?></span>
				<?php endif; ?>
			<?php endif; ?>
            </span>
	<?php endif; ?>
</td>
<td class="a-right"><?php echo $this->displayPriceAttribute('tax_amount') ?></td>
<td class="a-right"><?php echo $this->displayTaxPercent($_item) ?></td>
<td class="a-right"><?php echo $this->displayPriceAttribute('discount_amount') ?></td>
<td class="a-right last">


	<?php if ($helper->getVersionHelper()->isGe1600()) : ?>
		<?php echo $this->displayPrices(
			$_item->getBaseRowTotal() + $_item->getBaseTaxAmount() + $_item->getBaseHiddenTaxAmount() + $_item->getBaseWeeeTaxAppliedRowAmount() - $_item->getBaseDiscountAmount(),
			$_item->getRowTotal() + $_item->getTaxAmount() + $_item->getHiddenTaxAmount() + $_item->getWeeeTaxAppliedRowAmount() - $_item->getDiscountAmount()
		); ?>
	<?php else : ?>
		<?php echo $this->displayPrices(
			$_item->getBaseRowTotal() - $_item->getBaseDiscountAmount() + $_item->getBaseTaxAmount() + $_item->getBaseWeeeTaxAppliedRowAmount(),
			$_item->getRowTotal() - $_item->getDiscountAmount() + $_item->getTaxAmount() + $_item->getWeeeTaxAppliedRowAmount()
		); ?>
	<?php endif; ?>


</td>
</tr>

